### ISSUE TITLE
Paragraph for Fingerprint Door Lock

### ISSUE THREAD

**Issue by Ezcal** [Ezcal/ece411#3]
Descriptive paragraph for project idea to put in main proposal.

**Comment by cnels2** [comment]
In the Fingerprint Door Lock design, only authorized users are permitted access to a locked room. A user’s fingerprints are initially scanned and recorded onto the fingerprint sensor. When the user wants to access a room, they will scan their fingerprint again, thus creating a second image to compare to the original. The unique patterns of each fingerprint are analyzed and determined if there is a match. The fingerprint sensor is connected to a microcontroller. If the fingerprint image matches the original, the microcontroller will send a signal to a solenoid. The energized solenoid will unlock and the user will be allowed access to the room.
