### ISSUE TITLE
Paragraph for Heartbeat Sensor Project

### ISSUE THREAD

**Issue by Ezcal** [Ezcal/ece411#4]
Descriptive paragraph for project idea to put in main proposal.

**Comment by sabmah** [comment]
Pulse sensor will use infrared emitter and detector to detect a pulse from a finger tip. The pulse sensor uses infrared light reflected by the blood from the fingertip. It turns the mechanical pulse action into electrical signal.

Couple of ways to display the data:
1. Cascade of seven segment display.  
2. Graphic wave monitor

source: http://makezine.com/projects/ir-pulse-sensor/
